import React from "react";
import { Link, NavLink } from "react-router-dom";
import SiteHeader, { SiteFooter } from "../components/SiteHeader";
import PolicyContact from "../components/PolicyContact";
import "../policies.css";

const policies = {
  terms: {
    title: "Terms of service",
    introduction: "A clear understanding of your writing, our service, and what you can expect from Roundtable.",
    summary: "Your manuscript stays yours. Roundtable offers AI feedback to support your revisions; you make the creative decisions. Paid work uses credits, and monthly plans renew until you cancel.",
    sections: [
      ["about", "Who we are and these terms", <><p>Roundtable is an online manuscript feedback service operated by Linda Meng, a sole proprietor trading as Roundtable (“Roundtable”, “we”, “us”). These terms apply to your use of roundtable.works and the Roundtable application.</p><p>By creating an account or using the service, you agree to these terms. If you use Roundtable for an organisation, you must have authority to agree on its behalf. Our <Link to="/privacy/">Privacy policy</Link> explains how we handle personal information, and our <Link to="/refunds/">Refund policy</Link> forms part of these terms. Contact Linda Meng at <PolicyContact /></p></>],
      ["service", "What Roundtable provides", <><p>Roundtable lets you submit writing, choose AI reader perspectives, receive comments connected to your manuscript, and generate editorial feedback. Readers are simulated AI perspectives, not human readers or professional editors. Features and usage allowances are described on our <Link to="/pricing/">Pricing page</Link>.</p><p>AI feedback can be inaccurate, inconsistent, incomplete, or similar to feedback given to others. Review it before relying on it. We do not promise publication, increased sales, originality, or any particular creative outcome. Feedback is not legal advice, a copyright clearance, or a substitute for your own editorial judgment.</p></>],
      ["account", "Your account and responsible use", <><p>You must be at least 18 and legally able to enter a contract to use Roundtable. Provide accurate account information, keep your login secure, and tell us if you suspect unauthorised use. You are responsible for activity you authorise through your account.</p><p>Only upload work you own or have permission to process using this service. Do not infringe others’ rights, submit unlawful content, expose private information without a lawful basis, distribute malware, interfere with the service, bypass credit or security controls, or create accounts to abuse free allowances. Do not resell access without our written agreement.</p></>],
      ["ownership", "Your writing and generated feedback", <><p>You retain your rights in manuscripts, prompts, and other content you provide. You give us a limited, non-exclusive permission to store, copy, transmit, and process that content only as needed to provide the service, maintain its security, and respond to your support requests. This includes processing by the service providers described in our Privacy policy.</p><p>We do not acquire publishing rights to your manuscript or permission to use it in public marketing. As between you and Roundtable, you may use the feedback generated for you, including commercially; we assign to you any rights we may hold in that feedback, to the extent permitted by law. This does not guarantee that AI output is copyrightable, unique, or free of third-party rights.</p><p>Roundtable’s software, branding, and interface remain the property of their respective owners. Keep your own copies of manuscripts and important feedback; Roundtable is not a backup service.</p></>],
      ["payment", "Prices, credits, and payment", <><p>Prices on the Pricing page are in US dollars unless stated otherwise. The final amount, applicable taxes, currency, and billing interval are shown before you pay. Purchases made through Paddle are sold by Paddle as merchant of record and authorised reseller, under <a href="https://www.paddle.com/legal/buyer-terms">Paddle’s Buyer Terms</a>. We provide the Roundtable service; Paddle handles the payment transaction.</p><p>Credits are an allowance for AI processing, not money, a deposit, or a transferable asset. Reading length, panel size, model responses, reader setup, and additional reports affect consumption. Estimates shown before starting are not fixed quotes; a task may need more credits to finish. Failed model calls are not charged, but successfully completed work within a partly failed task may use credits.</p><p>Purchased packs and starter credits have no scheduled expiry. Monthly credits last for their paid billing period. On a consecutive paid renewal of a current plan, unused available monthly credits roll into the next cycle up to the new plan’s allowance. Rollover credits are used first, expire at the end of that cycle, and do not roll again. No paid renewal means no rollover. Existing legacy plans keep the rules disclosed when purchased until changed.</p><p>Credits are made available after payment is confirmed. A refund, reversal, or chargeback can remove the associated credits and may require review of your account balance. Credits already spent from a reversed purchase may be offset against remaining or future credits. This does not limit any right to a refund.</p></>],
      ["subscriptions", "Renewals, changes, and cancellation", <><p>Monthly subscriptions renew automatically each month until cancelled. Cancel before your next billing date through <Link to="/billing">Billing → Manage subscription</Link> or the subscription link provided by Paddle. Cancellation stops future renewals; it does not by itself refund the current period. Your current monthly allowance remains available until its normal expiry, and purchased and starter credits remain available.</p><p>Plan changes requested in Roundtable apply to the allowance at the next paid renewal, without an immediate prorated charge. Your existing allowance keeps its current expiry. We will give advance notice of changes to recurring prices so you can cancel before a new price applies. See our <Link to="/refunds/">Refund policy</Link> for refunds and cancellation rights.</p></>],
      ["availability", "Availability and ending access", <><p>We use reasonable care to provide Roundtable, but interruptions, maintenance, and third-party outages can occur. We do not promise uninterrupted access or a particular response time. We may improve or replace features without materially reducing a paid service without an appropriate remedy.</p><p>We may restrict or suspend access where reasonably necessary to address fraud, a material breach of these terms, a security risk, non-payment, or a legal requirement. Where practical, we will explain the reason and give you a chance to resolve it. Contact us if you think a restriction is mistaken.</p><p>You may stop using Roundtable and request account deletion at any time; cancel an active subscription as well. If we permanently discontinue the service or end paid access for reasons unrelated to your breach, we will provide reasonable notice where possible and arrange an appropriate refund for unused purchased credits and the undelivered part of a paid subscription through Paddle. Saved work is accessible during normal account operation even at zero credits; permanent storage is not guaranteed.</p></>],
      ["liability", "Responsibility and limits of liability", <><p>To the extent permitted by applicable law, the service and AI output are provided “as is” and “as available”, without implied warranties of fitness for a particular purpose, merchantability, or non-infringement. This does not replace our obligation to provide the service with reasonable care or any statutory guarantee.</p><p>To the extent permitted by law, we are not liable for indirect or consequential losses, lost profits, business opportunities, or publication outcomes arising from your use of Roundtable. Our total aggregate liability arising out of or relating to the service is limited to the greater of US$100 or the amount you paid for Roundtable in the 12 months preceding the event giving rise to the claim.</p><p>These exclusions and limits do not apply to fraud, wilful misconduct, gross negligence, death or personal injury caused by negligence, or any liability that cannot lawfully be excluded or limited. They do not reduce mandatory consumer remedies, refund rights, or rights under applicable data protection law. If you are a consumer, a limitation applies only to the extent it is lawful and fair under the law protecting you.</p></>],
      ["disputes", "Questions, disputes, and updates", <><p>Please contact Linda Meng at <PolicyContact /> to raise a concern. We will try to resolve it in good faith. Nothing in these terms requires arbitration, prevents a complaint to a regulator, or takes away access to courts or consumer protections available under applicable law. Applicable law determines the governing law and competent courts.</p><p>We may update these terms as the service or legal requirements change. We will post the revised date here and give reasonable advance notice of material changes, by email or in the service, unless a legal or urgent security reason requires an earlier change. Changes do not retroactively remove rights relating to earlier purchases. If a provision is unenforceable, the remaining terms continue to apply.</p></>],
    ],
  },
  privacy: {
    title: "Privacy policy",
    introduction: "Writing can be personal. Here is how your account information and manuscripts are handled when you use Roundtable.",
    summary: "Your draft stays yours. We do not publish your manuscript or use it to train AI, and we have opted out of training with our AI providers. We save your work so you can return to it and send relevant content to providers for feedback. You can delete manuscripts or request deletion; backup and provider retention can still apply.",
    sections: [
      ["controller", "Who handles your information", <><p>Linda Meng, the sole proprietor operating Roundtable at roundtable.works, is responsible for the personal information described in this policy and is its controller where applicable data protection law uses that term. For privacy questions or requests, contact <PolicyContact /></p><p>This policy covers the Roundtable website and application. Paddle separately handles purchase and payment data under its own <a href="https://www.paddle.com/legal/privacy">Privacy policy</a>.</p></>],
      ["information", "Information we collect", <><ul><li><strong>Account information:</strong> your name, email address, account identifiers, sign-in method, and verification status. Password sign-in stores a password hash, not a readable password. Google sign-in supplies basic profile information, which can include your name, email, and profile picture.</li><li><strong>Your work:</strong> uploaded or pasted manuscripts, titles, genre and audience details, reader preferences, questions, and generated reactions and reports.</li><li><strong>Usage and billing records:</strong> credit balances and consumption, processing status, purchase and subscription identifiers, payment status, and related transaction records. We do not receive your full payment card number from Paddle.</li><li><strong>Technical and support information:</strong> session identifiers, IP addresses and request information used for security and rate limiting, error and operational records, and information you send when asking for help.</li></ul><p>Please avoid including sensitive personal information or information about other people that is unnecessary for the feedback you want. Only submit material you are entitled to share with us and our processing providers.</p></>],
      ["connections", "Assistants you connect", <><p>If you create an assistant connection key, we store its name, permission, expiry, a short identifying prefix, and a hash of the key. We show the full key once. You can revoke it in Assistant connections.</p><p>A connected assistant can retrieve the manuscripts, reader notes, reports, and credit balance available to your account. If you grant reading permission, it can also submit manuscripts and request paid AI work using your account credits. The assistant provider receives the content it requests and handles it under its own policies; Roundtable?s provider training opt-outs do not govern an assistant you choose separately. Revocation blocks new requests, but work already accepted may finish and use credits.</p></>],
      ["purposes", "How and why we use it", <><p>We use account and manuscript information to authenticate you, run the readings you request, save results, provide support, and administer your credits and subscription. Where a legal basis is required, this processing is necessary to perform our contract with you or take steps you request before entering it.</p><p>We use limited technical and usage information to keep the service reliable, investigate errors, prevent fraud and abuse, and protect accounts. Where applicable, we rely on our legitimate interests in operating a secure service, balanced against your rights. We keep records necessary to comply with legal, tax, and accounting obligations on the basis of those obligations. Where consent is required for an optional use, we will ask separately, and you can withdraw it.</p><p>We do not sell your personal information or share it for cross-context behavioural advertising. Roundtable does not use manuscripts to train AI models, and we have opted out of training with our AI providers. Generating feedback does require processing by external AI providers, as explained below.</p></>],
      ["providers", "AI processing and other service providers", <><p>Relevant manuscript text, instructions, preferences, and earlier feedback may be sent to external AI providers to generate reader perspectives and editorial reports. This can include the full manuscript when the task requires it. Depending on the feature and model in use, providers may include Google, OpenAI, and Anthropic.</p><p>We have opted out of provider use of your content for AI training. Providers process requests under their applicable API terms and data handling settings and may retain content for service operation or safety monitoring. Training opt-outs do not mean zero retention. Contact us for details about the arrangements for a particular model.</p><p>We also use service providers for hosting, databases, authentication, and transactional email. Google handles Google sign-in when you choose it; Resend delivers account emails when that email service is enabled. These providers receive the information needed for their role. Paddle handles checkout, taxes, receipts, and subscription payment administration as merchant of record.</p><p>Access to your content may be necessary to investigate a support request, maintain security, or meet legal obligations. We may disclose information when required by law or reasonably necessary to protect rights and safety. If the service is transferred to a new operator, relevant information may be transferred subject to appropriate protection and notice.</p></>],
      ["storage", "Storage, retention, and international processing", <><p>We retain account information and saved manuscripts and feedback while needed to provide your account and saved workspace, unless you delete them or request deletion. Operational and support records are retained only for as long as needed to investigate issues, protect the service, and resolve requests. Billing and dispute records may need to be kept longer for accounting, legal obligations, fraud prevention, or legal claims.</p><p>You can delete a manuscript using the application’s deletion control and request account deletion by contacting us. Deletion from active systems may not immediately remove copies from backups or records that must be retained by law. Copies held by external providers follow their applicable retention arrangements. We can explain relevant retention criteria when you contact us.</p><p>We and our providers may process information in countries other than yours, where privacy laws may differ. Where applicable law requires safeguards for international transfers, these must include a recognised adequacy decision or appropriate contractual safeguards, such as standard contractual clauses. You can contact us for information about the arrangements applicable to your data.</p></>],
      ["cookies", "Cookies and security", <><p>We use anonymous daily counters to understand visits to public pages and clicks on signup links. These counters contain only a public page category, a broad referral category (such as Google or ChatGPT), the event type, date, and count. We do not store visitor identifiers, raw referrer URLs, query strings, or manuscript content in analytics, and do not set analytics cookies or use analytics browser storage. Counters are retained for up to 400 days and older counters are removed when new visits are recorded. We respect browser Do Not Track and Global Privacy Control signals by skipping these measurements. The dashboard is restricted to the verified site owner.</p><p>Roundtable uses session cookies to keep you signed in and a short-lived security cookie for Google sign-in. Blocking these cookies may prevent sign-in or account features from working. Paddle and Google may use their own cookies or similar technology when you open checkout or choose Google sign-in; their policies apply to those services.</p><p>We use safeguards such as password hashing, access controls, and session protections to protect personal information. No online service or storage system is completely secure. Keep your credentials private and contact us promptly if you suspect an account security issue.</p></>],
      ["rights", "Your choices and rights", <><p>Depending on where you live, you may have rights to access, correct, delete, or obtain a portable copy of your personal information; restrict or object to certain processing, including processing based on legitimate interests; and withdraw consent where processing relies on consent. These rights are subject to the conditions and exceptions in applicable law.</p><p>Send requests to <PolicyContact /> using your account email where possible. We may need to verify your identity, and we will respond within the time required by applicable law. You can also complain to your local data protection authority. We do not make decisions producing legal or similarly significant effects solely from the creative feedback generated about your writing.</p><p>You can stop submitting new work or close your account. Account deletion and subscription cancellation are separate requests: cancel through <Link to="/billing">Billing</Link> or Paddle to stop future renewals.</p></>],
      ["updates", "Age requirements and policy changes", <><p>Roundtable is intended for adults aged 18 and over. We do not knowingly collect personal information from children. Contact us if you believe a child has provided information so we can investigate and take appropriate steps.</p><p>We will update the date on this page when this policy changes and provide an email or in-product notice of material changes where appropriate or required. We will seek consent before a new use where the law requires it.</p></>],
    ],
  },
  refunds: {
    title: "Refund policy",
    introduction: "Room to try the service, clear cancellation terms, and a straightforward way to ask for help when something goes wrong.",
    summary: "Request a full refund within 14 days if you have not used credits from that purchase. Cancel a subscription before its next billing date to stop renewal. Service problems, billing mistakes, and statutory rights are handled separately.",
    sections: [
      ["unused", "Unused purchases: 14 days to request a refund", <><p>If you request a refund within 14 calendar days of payment and have not used any credits granted by that purchase, we offer a full refund. This applies to a one-time reading pack, your first monthly subscription payment, and a monthly renewal. Using free starter credits before a purchase does not by itself disqualify you.</p><p>Please stop using the credits you want refunded while the request is reviewed. This voluntary offer is in addition to any rights under applicable law or <a href="https://www.paddle.com/legal/refund-policy">Paddle’s Refund Policy</a>, not a replacement for them.</p></>],
      ["used", "Used credits and service problems", <><p>Once credits from a purchase have been used, or more than 14 days have passed, we do not ordinarily refund a change of mind or unused subscription time. AI feedback is subjective, so disagreement with an otherwise functioning reader or report does not, by itself, qualify for a discretionary refund.</p><p>If a technical fault prevents us from providing the purchased service, a payment is duplicated, or you believe credits were charged incorrectly, contact us with the details. We will investigate and provide an appropriate remedy, which may include restoring incorrectly charged credits, completing the service, or arranging a partial or full refund. This does not limit remedies you are entitled to by law.</p><p>A failed model call is not charged. If a longer task completes some work before failing, the successful work can still use credits. Tell us if your balance does not match the work delivered.</p></>],
      ["cancel", "How to cancel a subscription", <><p>Open <Link to="/billing">Billing</Link>, select “Manage subscription”, and cancel in Paddle’s customer portal before your next billing date. You can also use the subscription management link supplied by Paddle. If you cannot access those options, contact us or <a href="https://paddle.net">Paddle Buyer Support</a>.</p><p>Cancellation stops future renewals. You can use the current monthly allowance until the end of the paid period; without a consecutive paid renewal it does not roll over. Purchased packs and starter credits keep their normal availability. Cancellation does not automatically create a refund request, and a refund request does not necessarily cancel a subscription. If you want both, please say so.</p></>],
      ["request", "How to request a refund", <><p>Contact Linda Meng, the operator of Roundtable, at <PolicyContact /> or submit your request to <a href="https://paddle.net">Paddle Buyer Support</a>. Include your account email, payment date, Paddle receipt or transaction reference, and a short explanation. Never send a full card number, password, or an entire manuscript to identify a payment.</p><p>Paddle is the merchant of record for purchases made through its checkout and processes approved refunds to the original payment method. Processing and bank posting times vary; your refund confirmation will provide the available details. We do not issue refunds through an alternative payment method or require a fee to request one.</p><p>A full refund removes the credits or subscription entitlement associated with that payment; a partial refund may remove the corresponding portion. If refunded credits were already used, we may adjust your credit balance and review access to further paid AI work. This does not reduce your legal refund rights.</p></>],
      ["rights", "Your consumer rights come first", <><p>Nothing in this policy excludes rights to cancel or withdraw from a purchase, receive a refund, or obtain a remedy for a faulty, unavailable, or misdescribed service under applicable consumer law.</p><p>Some digital purchases carry a statutory withdrawal period. Whether it applies, and whether it ends or changes after immediate supply begins, depends on your location, the product, and the express consent and acknowledgements collected at checkout. Simply using this website does not waive those rights. Paddle’s Buyer Terms and Refund Policy govern the payment transaction, and any greater mandatory rights remain available.</p><p>This policy applies to purchases made while this version is in effect. Later changes will not reduce rights attached to an earlier purchase.</p></>],
    ],
  },
};

export default function PolicyPage({ kind }) {
  const policy = policies[kind];
  return <><SiteHeader /><main id="main-content" className="page-width policy-page" tabIndex={-1}>
    <nav className="policy-tabs" aria-label="Terms and policies"><NavLink to="/terms/">Terms of service</NavLink><NavLink to="/privacy/">Privacy policy</NavLink><NavLink to="/refunds/">Refund policy</NavLink></nav>
    <header className="policy-heading"><h1>{policy.title}</h1><p>{policy.introduction}</p><span>Last updated: September 8, 2026</span></header>
    <div className="policy-layout"><aside className="policy-contents no-print"><nav aria-label="On this page"><p>On this page</p>{policy.sections.map(([id, title]) => <a href={`#${id}`} key={id}>{title}</a>)}</nav><Link className="text-link" to="/pricing/">View pricing</Link></aside>
      <article className="policy-document" aria-label={policy.title}><div className="policy-summary"><h2>At a glance</h2><p>{policy.summary}</p><small>This overview is a guide. The full policy below applies.</small></div>{policy.sections.map(([id, title, content]) => <section id={id} key={id} aria-labelledby={`${id}-heading`}><h2 id={`${id}-heading`}>{title}</h2>{content}</section>)}<p className="policy-endnote">Roundtable. A little perspective for your next draft.</p></article>
    </div>
  </main><SiteFooter /></>;
}
